export const GET_ALL_PLANTS = "GET_ALL_PLANTS"
export const GET_WOODY_PLANTS = "GET_WOODY_PLANTS"
export const GET_NONWOODY_PLANTS = "GET_NONWOODY_PLANTS"
export const GET_FERNS_DATA = "GET_FERNS_DATA"
export const GET_GRASS_LIKE_PLANTS = "GET_GRASS_LIKE_PLANTS"
export const POST_USERDATA = "POST_USERDATA"
// export const POST_JSONDATA = "POST_JSONDATA"
export const POST_JSON_DATA_STATUS = "POST_JSON_DATA_STATUS"
export const GET_PLANT = "GET_PLANT"

//Selectors data
export const GET_HABITAT = "GET_HABITAT"
export const GET_FLOWER_PETAL_COLOR = "GET_FLOWER_PETAL_COLOR"
export const GET_LEAF_BLADE_EDGES = "GET_LEAF_BLADE_EDGES"
export const GET_LEAF_TYPE = "GET_LEAF_TYPE"
export const GET_LEAF_ARRANGEMENT = "GET_LEAF_ARRANGEMENT"
export const GET_COUNTY = "GET_COUNTY"
export const PLANT_FAMILY_DETAILS = "PLANT_FAMILY_DETAILS"

//Toggle selectors
export const TOGGLE_PLANT_TYPE = "TOGGLE_PLANT_TYPE"
export const TOGGLE_TYPE = "TOGGLE_TYPE"
export const TOGGLE_HABITAT = "TOGGLE_HABITAT"
export const TOGGLE_FLOWER_PETAL_COLOR = "TOGGLE_FLOWER_PETAL_COLOR"
export const TOGGLE_FRUITS = "TOGGLE_FRUITS"
export const TOGGLE_FRUIT_COLOR = "TOGGLE_FRUIT_COLOR"
export const TOGGLE_LIP_SHAPE = "TOGGLE_LIP_SHAPE"
export const TOGGLE_LEAF_BLADE_EDGES = "TOGGLE_LEAF_BLADE_EDGES"
export const TOGGLE_LEAF_TYPE = "TOGGLE_LEAF_TYPE"
export const TOGGLE_LEAF_ARRANGEMENT = "GET_LEAF_ARRANGEMENT"
export const TOGGLE_LEAF_DURATION = "TOGGLE_LEAF_DURATION"
export const TOGGLE_LEAFLET_DIVISIONS = "TOGGLE_LEAFLET_DIVISIONS"
export const TOGGLE_SPORE_SHAPE = "TOGGLE_SPORE_SHAPE"
export const TOGGLE_SPORE_LOCATION = "TOGGLE_SPORE_LOCATION"
export const TOGGLE_SPORE_COVERING = "TOGGLE_SPORE_COVERING"
export const TOGGLE_SPORE_UNDER_LEAF = "TOGGLE_SPORE_UNDER_LEAF"
// export const TOGGLE_COUNTY = "TOGGLE_COUNTY"
export const TOGGLE_INFLORESCENCE = "TOGGLE_INFLORESCENCE"
export const TOGGLE_NATIVE = "TOGGLE_NATIVE"
export const TOGGLE_STEMS = "TOGGLE_STEMS"
export const TOGGLE_GROWTH_FORM = "TOGGLE_GROWTH_FORM"
export const TOGGLE_SHAPE = "TOGGLE SHAPE"
export const TOGGLE_PETAL_SYMMETRY = "TOGGLE_PETAL_SYMMETRY"
//Selector
export const SELECTOR_FILTER = "SELECTOR_FILTER"
export const FILTER_CHECKED = "FILTER_CHECKED"
export const SELECTED_FILTER_LIST = "SELECTED_FILTER_LIST"
export const ACTIVE_SELECTOR_LIST = "ACTIVE_SELECTOR_LIST"

export const IS_LOADING = "IS_LOADING"

//Search
export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS"

//Pagination
export const SET_ITEM_OFFSET = "SET_ITEM_OFFSET"
export const SET_PAGE_COUNT = "SET_PAGE_COUNT"
export const RESET_PAGE_COUNT = "RESET_PAGE_COUNT"
export const TOGGLE_PAGINATION = "TOGGLE_PAGINATION"
export const GET_ALL_PLANTS_COUNT = "GET_ALL_PLANTS_COUNT"
export const GET_ALL_NONWOODY_PLANTS_COUNT = "GET_ALL_NONWOODY_PLANTS_COUNT"
export const GET_ALL_WOODY_PLANTS_COUNT = "GET_ALL_WOODY_PLANTS_COUNT"
export const IS_ERROR= 'IS_ERROR'
export const IS_ERROR_SEARCH = 'IS_ERROR_SEARCH'
//Popover
export const GET_POPOVER_DATA = "GET_POPOVER_DATA"
export const TRIGGER_TOOLTIP_POPUP = "TRIGGER_TOOLTIP_POPUP"

//Authentication
export const AUTHENTICATION_STATE = "AUTHENTICATION_STATE"
export const ALL_PLANTS ="ALL_PLANTS"